wotapi_thing.wotapi_thing_type.*:
  type: config_entity
  label: 'Thing type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    at_type:
      type: array
      label: 'at_type'
