wotapi_property.wotapi_property_type.*:
  type: config_entity
  label: 'Property type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    title:
      type: text
      label: 'Title'
    description:
      type: text
      label: 'Description'
    at_type:
      type: text
      label: 'at_type'
    type:
      type: text
      label: 'type'
    unit:
      type: text
      label: 'unit'
